#   libzmq

language: c

os:
- linux
- osx

sudo: false

env:
 global:
  - BUILD_PREFIX=$PWD/tmp
  - CFLAGS=-I${BUILD_PREFIX}/include
  - CPPFLAGS=-I${BUILD_PREFIX}/include
  - CXXFLAGS=-I${BUILD_PREFIX}/include
  - LDFLAGS=-L${BUILD_PREFIX}/lib
  - PKG_CONFIG_PATH=${BUILD_PREFIX}/lib/pkgconfig
  - DISTCHECK_CONFIGURE_FLAGS="--with-libsodium --prefix=${BUILD_PREFIX}"

#   Build required projects first
before_script:

- mkdir tmp
#   libsodium
- git clone --depth 1 -b stable git://github.com/jedisct1/libsodium.git
- ( cd libsodium; ./autogen.sh; ./configure --prefix=${BUILD_PREFIX}; make check; make install )

# ZMQ stress tests need more open socket (files) than the usual default
# On OSX, it seems the way to set the max files limit is constantly changing, so
# try to use all known knobs to ensure compatibility across various versions
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; fi

#   Build and check this project
script:
- ./autogen.sh && ./configure --with-libsodium --prefix=${BUILD_PREFIX} && make distcheck

# Deploy tags
before_deploy:
- . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: "VIOyO6gR+E4PH9i48eq8gF15PYTZamUOLwbaa4nnwCgmKy+iiwIrXBF/FZ9SdzjeUUSrK0v1gAfC389U+ZBjdD0NQTcSZ9UngvSALgtI7w4gQMJ09G74Sowcm21PIO/Pn3V4xpO0ciJ7xb2aGP6zhbGOiK/nmv8MXUM/PzxvH6A="
  file_glob: true
  file: ${ZEROMQ4X_DEPLOYMENT}
  skip_cleanup: true
  on:
    repo: zeromq/zeromq4-x
    branch: master
    tags: true
    condition: "$TRAVIS_OS_NAME =~ (linux)"
